load("@rules_python//python:defs.bzl", "py_binary")
load("@pypi//:requirements.bzl", "requirement")

py_binary(
    name = "embed",
    srcs = ["embed.py"],
    data = [
        ".env",
    ],
    main = "embed.py",
    deps = [
        requirement("chonkie"),
        requirement("google-genai"),
        requirement("python-dotenv"),
        requirement("requests"),
    ],
)

py_binary(
    name = "cluster",
    srcs = ["cluster.py"],
    data = [
        ".env",
    ],
    main = "cluster.py",
    deps = [
        requirement("python-dotenv"),
    ],
)

py_binary(
    name = "index",
    srcs = ["index.py"],
    data = [
        ".env",
    ],
    main = "index.py",
    deps = [
        requirement("python-dotenv"),
        requirement("requests"),
    ],
)


